### PR TITLE
Add mplhep figures

### PR DESCRIPTION
**Pull request by LovelyBuggies**

### CODE REVIEW

**Comment by LovelyBuggies** [comment]
@henryiii Code snippet you might use in the paper:

```python
import mplhep

mplhep.histplot(hist_1d)

w, xbins, ybins = hist_2d.to_numpy()
mplhep.hist2dplot(w.T, xbins, ybins)
```

**Comment by henryiii** [comment]
Do we still have to use to_numpy for mplhep, I guess?

**Comment by henryiii** [comment]
I am 90% sure that you can pass a histogram directly to histplot. See https://github.com/scikit-hep/mplhep/blob/9804f1dc97e593034509aaa23933c50fb8e8bd95/mplhep/plot.py#L50

Hist2D plots, not yet. :(

**Comment by henryiii** [comment]
I'll force push to your branch to rebase and remove the already-merged comments, hope you don't mind. Use `git reset HEAD` or `git reset --hard HEAD` after a fetch (removes current modifications!) if you need to sync on this branch.

**Comment by LovelyBuggies** [comment]
~~UR right, we don't need to use to_numpy. I am making changes on the code snippet above. Thanks for your suggestion.~~

@henryiii Update: **You are totally right**. After testing, I found hist_2d is not capable (`ValueError: More than 1 axis`), but hist_1d is okay.


```python
import mplhep

mplhep.histplot(hist_1d)

w, xbins, ybins = hist_2d.to_numpy()
mplhep.hist2dplot(w.T, xbins, ybins)
```

**Pull request merged**
