### PR TITLE
Add eg fig

### PR DESCRIPTION
**Pull request by LovelyBuggies**
@henryiii Do you mean this? https://github.com/henryiii/scipy_proceedings/issues/1#issuecomment-635988035

### CODE REVIEW

**Comment by LovelyBuggies** [comment]
Not sure about the layout. I did not compile tex, I am just reading in rst.

**Comment by henryiii** [comment]
Can you break that into two separate plots? I'd like to have two separate examples here, rather than making one too long. Otherwise, that's about right.

**Comment by LovelyBuggies** [comment]
> Can you break that into two separate plots? I'd like to have two separate examples here, rather than making one too long. Otherwise, that's about right.

@henryiii okay, I ~~will~~ have seperated the pdf, and you can fine-tune the layout now.

**Comment by henryiii** [comment]
Thanks!

**Comment by LovelyBuggies** [comment]
Not sure about the layout, I did not try to build tex.

**Comment by LovelyBuggies** [comment]
Not sure about the layout, I did not try to build tex.

**Comment by henryiii** [comment]
No problem, I'm adjusting as I go through and add references.

**Pull request merged**
